config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "tasks", to:"tasks#index"
  get '/tasks/show/:id', to: 'tasks#show', as: 'task'
  get '/tasks/new', to: 'tasks#new', as: 'new_task'
  post '/tasks', to: 'tasks#create'

  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.all
        @task = Task.new
    end

    def update
        @task = Task.find(params[:id])
        @task.update(task_params)
        redirect_to tasks_path
    end

    def show
        @task = Task.find(params[:id]) unless params[:id] == 'new'
        @task ||= Task.new
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        if @task.save
            redirect_to tasks_path
        else
            render :new
        end
    end

    private

    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
    <% @tasks.each do |task| %>
        <li>
            <input type="checkbox" name="task_ids[]" value="<%= task.id %>" <%= task.completed ? 'checked' : '' %>>
            <%= link_to task.title, task_path(task) %>
        </li>
    <% end %>
</ul>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<%= form_with(model: @task, url: tasks_path) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= form_for @task, url: task_path(@task), method: :put do |f| %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back', tasks_path %>